service: explorer

custom:
    authorizer:
        arn: arn:aws:cognito-idp:eu-west-1:288636345286:userpool/eu-west-1_Qxql5FxDZ
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
        identityValidationExpression: '.*'


provider:
  name: aws
  runtime: python3.7
  stage: prod
  region: eu-west-1

functions:
  urls:
    handler: handler.create
    events:
      - http:
          path: /urls
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer}
      - http:
          path: /urls
          method: OPTIONS
          cors: true

        
      
