// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:6f3d4be0-9f9e-4230-af35-e7c69087262b",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_LC138fakr",
    "aws_user_pools_web_client_id": "3r7gngb9bc66tsp4v0q0v0mnjc",
    "aws_cloud_logic_custom": [
        {
            "name": "urls",
            "endpoint": "https://7qgd34ctw5.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
